# Generated by Django 6.0.6 on 2026-07-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='advance_amount',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Amount paid in advance (only when payment_type=advance). Immediately deducted from cash_in_hand on draft creation. Capped at net_payable on confirmation.', max_digits=18),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='payment_type',
            field=models.CharField(choices=[('advance', 'Advance Payment'), ('after_delivery', 'Payment After Delivery')], default='after_delivery', help_text='Advance payment or payment after delivery.', max_length=20),
        ),
    ]
