# Generated by Django 6.0.6 on 2026-06-28 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_invoice_cash_received_invoice_credit_received_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='grand_total',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='invoice',
            name='gst_total',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='invoice',
            name='wht_total',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='discount',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Positive = price reduction. Negative = surcharge. effective_price = selling_price - discount', max_digits=10),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='effective_price',
            field=models.DecimalField(decimal_places=4, default=0, help_text='selling_price - discount', max_digits=14),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='gst',
            field=models.DecimalField(decimal_places=2, default=0, help_text='GST % e.g. 18.5', max_digits=5),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='line_gross',
            field=models.DecimalField(decimal_places=4, default=0, help_text='quantity x effective_price', max_digits=18),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='line_gst_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='line_wht_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='wht',
            field=models.DecimalField(decimal_places=2, default=0, help_text='WHT % e.g. 1.5', max_digits=5),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='line_total',
            field=models.DecimalField(decimal_places=4, default=0, help_text='line_gross + line_gst - line_wht (tax-inclusive)', max_digits=18),
        ),
        migrations.CreateModel(
            name='SavedInvoicePDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(help_text='User-supplied or default name.', max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('is_draft', models.BooleanField(default=False, help_text='True if saved with DRAFT watermark.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_pdfs', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saved_pdfs', to='billing.invoice')),
                ('saved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_pdfs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Invoice PDF',
                'verbose_name_plural': 'Saved Invoice PDFs',
                'ordering': ['-created_at'],
            },
        ),
    ]
