# Generated by Django 6.0.6 on 2026-07-20 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('purchases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOpeningBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_opening_balances_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='opening_balance', to='billing.customer')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='opening_balance', to='billing.invoice')),
            ],
            options={
                'verbose_name': 'Customer Opening Balance',
                'verbose_name_plural': 'Customer Opening Balances',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OpeningCashEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(default='Opening cash added via data entry', max_length=255)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opening_cash_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Opening Cash Entry',
                'verbose_name_plural': 'Opening Cash Entries',
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierOpeningBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_opening_balances_created', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='opening_balance', to='purchases.purchaseorder')),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='opening_balance', to='purchases.supplier')),
            ],
            options={
                'verbose_name': 'Supplier Opening Balance',
                'verbose_name_plural': 'Supplier Opening Balances',
                'ordering': ['-created_at'],
            },
        ),
    ]
