# Generated by Django 6.0.6 on 2026-06-30 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selling_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rate_creates', to=settings.AUTH_USER_MODEL)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='rate', to='purchases.product')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rate_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Rate',
                'verbose_name_plural': 'Product Rates',
                'ordering': ['product__name'],
            },
        ),
        migrations.CreateModel(
            name='ProductRateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selling_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, default='', help_text='Optional reason for price change.', max_length=255)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rate_history_changes', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rate_history', to='purchases.product')),
            ],
            options={
                'verbose_name': 'Product Rate History',
                'verbose_name_plural': 'Product Rate Histories',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['product', '-changed_at'], name='idx_rate_history_product_date')],
            },
        ),
    ]
