# Generated by Django 6.0.6 on 2026-07-20 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=255)),
                ('supplier_code', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ledger', to='purchases.supplier')),
            ],
            options={
                'verbose_name': 'Supplier Ledger',
                'verbose_name_plural': 'Supplier Ledgers',
                'ordering': ['supplier_name'],
            },
        ),
        migrations.CreateModel(
            name='SavedLedgerPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_ledger_pdfs', to=settings.AUTH_USER_MODEL)),
                ('saved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_ledger_pdfs', to=settings.AUTH_USER_MODEL)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saved_pdfs', to='ledger.supplierledger')),
            ],
            options={
                'verbose_name': 'Saved Ledger PDF',
                'verbose_name_plural': 'Saved Ledger PDFs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('purchase', 'Purchase'), ('payment', 'Payment'), ('return', 'Return'), ('advance', 'Advance Payment'), ('opening_balance', 'Opening Balance')], db_index=True, max_length=20)),
                ('date', models.DateField(db_index=True)),
                ('details', models.CharField(max_length=500)),
                ('reference', models.CharField(db_index=True, max_length=50)),
                ('debit', models.DecimalField(decimal_places=4, default=0, help_text='Money we paid to supplier (payment/return/advance).', max_digits=18)),
                ('credit', models.DecimalField(decimal_places=4, default=0, help_text='Amount we owe supplier (purchase confirmed).', max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries_created', to=settings.AUTH_USER_MODEL)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='ledger.supplierledger')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='purchases.purchaseorder')),
                ('purchase_return', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='purchases.purchasereturn')),
                ('supplier_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='purchases.supplierpayment')),
            ],
            options={
                'verbose_name': 'Supplier Ledger Entry',
                'verbose_name_plural': 'Supplier Ledger Entries',
                'ordering': ['date', 'created_at'],
                'indexes': [models.Index(fields=['ledger', 'date'], name='idx_ledger_entry_date')],
            },
        ),
        migrations.CreateModel(
            name='SupplierLedgerSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.CharField(db_index=True, help_text='Format: YYYY-MM e.g. 2026-06', max_length=7)),
                ('closing_balance', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='ledger.supplierledger')),
            ],
            options={
                'verbose_name': 'Supplier Ledger Snapshot',
                'verbose_name_plural': 'Supplier Ledger Snapshots',
                'ordering': ['year_month'],
                'unique_together': {('ledger', 'year_month')},
            },
        ),
    ]
